version: 1

sources:

  - name: dados_educacao                 # Nome aleatório para se referir ao schema
    schema: public                       # Schema utilizado no projeto(default)
    tables:
      - name: staging_situacao_alunos    # tabela que usamos para a área de staging
